application: proyecto
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /templates
  static_dir: templates
  application_readable: true

- url: /showMovie/.+
  script: handlers.movies.showMovie.app
  login: required

- url: /movies
  script: handlers.movies.listMovie.app
  login: required

- url: /addMovie
  script: handlers.movies.addMovie.app
  login: required

- url: /addComment
  script: handlers.comments.addComment.app
  login: required

- url: /addMovieList
  script: handlers.mylist.addMovieList.app
  login: required

- url: /showMoviesList
  script: handlers.mylist.showMoviesList.app
  login: required

- url: /
  script: handlers.welcome.app










libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "latest"

- name: PIL
  version: "latest"
